version: '3.8'

services:

  gunicorn:
    image: chart_image
    command: sh -c gunicorn --bind 0.0.0.0:8000 app.wsgi

    volumes:
#      - ./project:/ChartProject
      - static_data:/ChartProject/main/static/

    expose:
      - 8000
    environment:
      - DATABASE_URL=postgresql://django:chart_db@db:5432/Kirill
      - DEBUG=1

  postgres:
    container_name: chart_postgres_db
    image: postgres
    expose:
      - 5432

    ports:
      - 5432:5432

    environment:

      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

    depends_on:
      - gunicorn

#  backend:
#    container_name: django_chart_container
#    image: chart_image
#    command: python manage.py runserver 0.0.0.0:8000
#
#    ports:
#      - 8000:8000
#
#    depends_on:
#    - postgres

  nginx:
     container_name: nginx_chart_container
     image: nginx

     dockerfile: ./nginx_default_settings/Dockerfile

    ports:
      - 80:80

    restart: unless-stopped
    tty: true

    volumes:
      - ./nginx/-conf.d:etc/nginx/conf.d

    depends_on:
    - gunicorn





